version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./webhook.py:/app/webhook.py  # For development hot-reload
    command: ["uvicorn", "webhook:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# version: '3.8'
# services:
#   webhook:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./server.key:/app/server.key
#       - ./server.crt:/app/server.crt
#     command: ["uvicorn", "webhook:app", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile=/app/server.key", "--ssl-certfile=/app/server.crt"]