apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-validator
webhooks:
- name: validate.pod.example.com
  clientConfig:
    service:
      name: webhook-service
      namespace: default
      path: "/validate"
      # url: "https://external-webhook.example.com:8000/validate"  # External URL
    caBundle: "<base64-encoded-ca-cert>"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None