apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lconnell/kubernetes-playground.git
    targetRevision: main  # Or test-action if still on that branch
    path: kustomize
    directory:
      include: "dev/kustomization.yaml"
  destination:
    server: https://kubernetes.default.svc  # In-cluster API server
    namespace: development  # Matches kustomize/dev/ namespace
  syncPolicy:
    automated:
      prune: true  # Deletes resources not in Git
      selfHeal: true  # Reverts manual changes
    syncOptions:
      - CreateNamespace=true  # Creates the dev namespace if missing