apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../api.yaml
- ../db.yaml

namespace: development

commonLabels:
  env: development

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api
  spec:
    replicas: 1  # Dev: 1 replica
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: db
  spec:
    replicas: 1  # Dev: 1 replica