apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: dev
nameSuffix: -dev
labels:
  - includeSelectors: true
    pairs:
      env: dev
patches:
  - target:
      kind: Deployment
      name: api
    path: patch-api.yaml
  - target:
      kind: StatefulSet
      name: db
    path: patch-db.yaml
  - target:
      kind: Secret
      name: db-secret
    path: patch-db-secret.yaml
configurations:
  - name-reference.yaml
