apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/api.yaml
- ../base/db.yaml

namespace: development


labels:
- includeSelectors: true
  pairs:
    env: development
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api
    spec:
      replicas: 1  # Dev: 1 replica
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: db
    spec:
      replicas: 1  # Dev: 1 replica
