apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api/kustomization.yaml
  - db/kustomization.yaml
namespace: development
nameSuffix: -dev
labels:
  - includeSelectors: true
    pairs:
      env: development
configurations:
  - name-reference.yaml
