apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api  # Matches api-dev pod labels
  ports:
    - protocol: TCP
      port: 80      # Service port (cluster-facing)
      targetPort: 80  # Nginx container port
  type: NodePort