apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db  # Matches db-dev pod labels
  ports:
    - protocol: TCP
      port: 5432  # Postgres default
      targetPort: 5432
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet