apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api.yaml
  - api-secret.yaml
  - db.yaml
  - db-secret.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf