name: Validate Kubernetes YAML
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    container: ghcr.io/yannh/kubeconform:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: apk add --no-cache curl bash
      - name: Install Kustomize
        run: |
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_v5.4.1_linux_amd64.tar.gz" | tar -xz
          mv kustomize /usr/local/bin/
      - name: Validate rendered manifests
        run: |
          for env in dev prod; do
            kustomize build kustomize/$env > /tmp/$env.yaml || exit 1
            /kubeconform -strict -summary /tmp/$env.yaml || exit 1
          done