name: Validate Kubernetes YAML
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    container: ghcr.io/yannh/kubeconform:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Validate Kubernetes manifests
        run: kubeconform -strict -summary *.yaml