name: Validate Kubernetes YAML
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    container: ghcr.io/yannh/kubeconform:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && mv kustomize /usr/local/bin/
      - name: Validate rendered manifests
        run: |
          for env in dev prod; do
            kustomize build kustomize/$env > /tmp/$env.yaml || exit 1
            /kubeconform -strict -summary /tmp/$env.yaml || exit 1
          done
