apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../api.yaml
- ../db.yaml

namespace: production

commonLabels:
  env: production

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api
  spec:
    replicas: 3  # Prod: 3 replicas
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: db
  spec:
    replicas: 1  # Prod: 1 replica (DB often stays at 1 unless clustered)
    template:
      spec:
        containers:
        - name: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"